# Generated by Django 5.0.4 on 2024-05-11 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinopoisk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='player',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
