# Generated by Django 5.0.4 on 2024-05-11 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinopoisk', '0002_movie_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_file',
            field=models.FileField(blank=True, null=True, upload_to='kinopoisk/videos/movies/movie_files/'),
        ),
    ]
